### PR TITLE
Bochscpu: edge coverage

### PR DESCRIPTION
**Pull request by clslgrnc**
Enable edge coverage for the Bochscpu backend

### CODE REVIEW

**Comment by 0vercl0k** [comment]
Amazing! Let me review this when I'm back from Hexacon 🙂

Cheers

**Comment by 0vercl0k** [comment]
I tried to fix up a few things, mainly removing the special path for the `before_execution` hook. After thinking about it, it should be fine, but let me know if I am missing anything!

Cheers

**Comment by clslgrnc** [comment]
My initial intent was to replace the RIP coverage with edge coverage, I also expected the option to only be used in the fuzz mode.
`BochscpuBackend_t::BeforeExecutionHookNoCover` is thus a copy of `BochscpuBackend_t::BeforeExecutionHook` without RIP coverage and trace generation, while still processing breakpoints.

In terms of exploration, it probably does not matter. Having the RIP actually helps when combining bochscpu with other fuzzers running the KVM backend. After running the bochscpu edge fuzzers on the initial corpus, starting KVM backends would add spurious samples to the corpus if RIP was not registered as coverage.
On the other end, not registering RIP might be slightly faster.

I do not have any strong opinion on the matter

I did not thought about the edges stats, that's great.

**Comment by 0vercl0k** [comment]
Also tagging @yrp604 to take a look at this whenever he has a minute.

Cheers

**Comment by yrp604** [comment]
This looks good to me.

There are major perf advantages if we can avoid the overhead of per-instruction hooks which this gets us closer to switching to. With this plus something like the kvm breakpoint strategy it might be possible?

**Comment by 0vercl0k** [comment]
That's a good idea - I don't think it should be hard to move away from those callbacks actually. If I'm not mistaken, we're only using them for coverage, tracing and breakpoints. We'd just need to turn on edge coverage by default and implement breakpoints without the hook. I filed #141 to investigate the speed-up and implement if it looks good.

I am currently pushing a few changes to `bxcpu` so will wait for them to land, update `wtf`'s version and land this 🍾😃

Cheers

**Comment by 0vercl0k** [comment]
Okay all the bxcpu changes have landed, I've updated the header / the binaries. I've run it through old snapshot / traces and there seems to be an issue somewhere.. I'll have to debug what's going on tomorrow 😔.

Cheers

**Comment by 0vercl0k** [comment]
Okay I investigated what was going on. Basically, the old dump I ran my test one must have been dumped with an old version of `bdump` with a `mxcsr_mask` set to `0`. Until now this didn't matter because of the bug found in #140. But now that this bug is fixed trying to execute `ldmxcsr` will trigger a #GP. Note that `bdump` has been fixed in https://github.com/yrp604/bdump/commit/5a86bdc45acaf65a32aa9149ea47b717d899c85e to set it to a 'sane' default value, and I've added code in `SanitizeCpuState` that will do the same if a dump is loaded with an `mxcsr_mask` set to 0 to not break users of new wtf with an old dump.

I've run a trace through an old dump and they are now the same which is great:
```
>fc output_old.txt output_new.txt
Comparing files output_old.txt and OUTPUT_NEW.TXT
***** output_old.txt
Setting debug register status to zero.
Running targets\ida64_dmp\ntfs-3g
***** OUTPUT_NEW.TXT
Setting debug register status to zero.
Setting mxcsr_mask to 0xffbf.
Running targets\ida64_dmp\ntfs-3g
*****

***** output_old.txt
      Memory accesses: 1933930864 bytes (1844 MB)
#1 cov: 267759 exec/s: 0.0 lastcov: 0.0s crash: 0 timeout: 0 cr3: 0 uptime: 1.3min
***** OUTPUT_NEW.TXT
      Memory accesses: 1933930864 bytes (1844 MB)
       Edges executed: 0 (0 unique)
#1 cov: 267759 exec/s: 0.0 lastcov: 0.0s crash: 0 timeout: 0 cr3: 0 uptime: 1.6min
*****
``` 

@clslgrnc I'm not sure if you still have old dump / states, but it'd be nice if you could give this a shot as well to build confidence but no worries if you have moved on / have no more time to spend on this, I understand 🙂

I'll try to bench perfs between the two versions and if I don't hear back in a week or so will merge as is!

Cheers

**Comment by clslgrnc** [comment]
> @clslgrnc I'm not sure if you still have old dump / states, but it'd be nice if you could give this a shot as well to build confidence but no worries if you have moved on / have no more time to spend on this, I understand slightly_smiling_face

Unfortunately my disk died recently. I did not backup my dumps and I won't have time to generate new ones before next year.

Thanks for the good work

best

**Comment by 0vercl0k** [comment]
No worries at all Colas, I hope you didn't lose anything important 🤞🏽😅

Cheers

**Comment by clslgrnc** [comment]
> No worries at all Colas, I hope you didn't lose anything important 🤞🏽sweat_smile Cheers

Fortunately no
Thanks

**Pull request merged**
